SonarSource-VisualStudio/sonaranalyzer-dotnet

src/SonarLint/Rules/DisposableNotDisposed.cs
src/Tests/SonarLint.UnitTest/TestCases/DisposableNotDisposed.cs

#83 Rule S2930 reports false positives for generated WinForms

---

src/SonarLint/Rules.Description/S2761.html
src/SonarLint/Rules/UnaryPrefixOperatorRepeated.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.RulingTest/Expected/S2761.json
src/Tests/SonarLint.RulingTest/SonarLint.RulingTest.csproj
src/Tests/SonarLint.UnitTest/Rules/UnaryPrefixOperatorRepeatedTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/UnaryPrefixOperatorRepeated.cs

#64 Doubled prefix operators "!!" and "~~" should not be used

---

src/SonarLint/Rules.Description/S2197.html
src/SonarLint/Rules/EqualityOnModulus.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.UnitTest/Rules/EqualityOnModulusTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/EqualityOnModulus.cs

#86 Rule S2197 should not report on unsigned values

---

src/SonarLint/Rules/ThreadStaticNonStaticField.cs

Issue #111 Fade out ThreadStatic attribute on non-static fields

---

src/SonarLint/Rules/RedundantCast.cs
src/Tests/SonarLint.UnitTest/TestCases/RedundantCast.cs

Issue #110 Fade out redundant casts and fix error location

---

src/SonarLint/Rules/GenericTypeParameterUnused.cs

Issue #109 Fade out unused generic type parameters

---

src/SonarLint/Helpers/ProjectTypeHelper.cs
src/SonarLint/Rules.Description/S3237.html
src/SonarLint/Rules/UseValueParameter.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.RulingTest/Expected/S3237.json
src/Tests/SonarLint.RulingTest/SonarLint.RulingTest.csproj
src/Tests/SonarLint.UnitTest/Rules/UseValueParameterTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/UseValueParameter.cs
src/Tests/SonarLint.UnitTest/TestCases/UseValueParameterInTest.cs
src/Tests/SonarLint.UnitTest/Verifier.cs

#74 "value" parameter is not used

---

src/SonarLint/Rules.Description/S3244.html
src/SonarLint/Rules/AnonymousDelegateEventUnsubscribe.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.RulingTest/Expected/S3244.json
src/Tests/SonarLint.RulingTest/SonarLint.RulingTest.csproj
src/Tests/SonarLint.UnitTest/Rules/AnonymousDelegateEventUnsubscribeTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/AnonymousDelegateEventUnsubscribe.cs

#72 Anonymous delegates should not be used to unsubscribe from Events

---

src/SonarLint/Rules.Description/S3172.html
src/SonarLint/Rules/DelegateSubtraction.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.RulingTest/Expected/S3172.json
src/Tests/SonarLint.RulingTest/SonarLint.RulingTest.csproj
src/Tests/SonarLint.UnitTest/Rules/DelegateSubtractionTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/DelegateSubtraction.cs

#57 Delegates should not be subtracted

---

src/SonarLint/Rules/DisposableNotDisposed.cs
src/SonarLint/Rules/DisposeFromDispose.cs
src/SonarLint/Rules/DisposeNotImplementingDispose.cs

Issue #131 Rules on disposables fail when the "IDisposable.Dispose" method can't be found

---

src/SonarLint.Extra/Common/Metrics.cs
src/SonarLint/Rules/CommentedOutCode.cs

Issue #130 CommentedCode rule S125 fails when typing "/*" at the end of an existing file

---

src/SonarLint/Rules.Description/S3217.html
src/SonarLint/Rules/ForeachLoopExplicitConversion.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.RulingTest/Expected/S3217.json
src/Tests/SonarLint.RulingTest/SonarLint.RulingTest.csproj
src/Tests/SonarLint.UnitTest/Rules/ForeachLoopExplicitConversionTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/ForeachLoopExplicitConversion.cs

#77 Covariance should not be used in "foreach" loops

---

src/SonarLint/Rules/EmptyStatement.cs

Issue #121 Fade out unnecessary empty statements

---

src/SonarLint/Rules.Description/S3169.html
src/SonarLint/Rules/OrderByRepeated.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.RulingTest/Expected/S3169.json
src/Tests/SonarLint.RulingTest/SonarLint.RulingTest.csproj
src/Tests/SonarLint.UnitTest/Rules/OrderByRepeatedTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/OrderByRepeated.cs

Issue #62 Multiple "OrderBy" calls should not be used

---

src/SonarLint/Rules/BooleanLiteralUnnecessary.cs

Issue #108 Fade out unnecessary boolean literals, and fixing quality flaw

---

src/SonarLint/Rules.Description/S3215.html
src/SonarLint/Rules/CastConcreteTypeToInterface.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.RulingTest/Expected/S3215.json
src/Tests/SonarLint.RulingTest/SonarLint.RulingTest.csproj
src/Tests/SonarLint.UnitTest/Rules/CastConcreteTypeToInterfaceTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/CastConcreteTypeToInterface.cs

#63 Don’t cast from an interface to a concrete type

---

src/SonarLint/Rules.Description/S3234.html
src/SonarLint/Rules/SuppressFinalizeUseless.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.RulingTest/Expected/S3234.json
src/Tests/SonarLint.RulingTest/SonarLint.RulingTest.csproj
src/Tests/SonarLint.UnitTest/Rules/SuppressFinalizeUselessTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/SuppressFinalizeUseless.cs

Issue #73 "GC.SuppressFinalize" is invoked for type without destructor

---

src/SonarLint/Rules/CommentedOutCode.cs
src/Tests/SonarLint.RulingTest/Expected/S125.json
src/Tests/SonarLint.UnitTest/TestCases/CommentedOutCode.cs

Issue #89 False positive on Rule S125 (commented out code)

---

its/ValidationRuleset.ruleset
src/SonarLint/Rules.Description/S3218.html
src/SonarLint/Rules/MemberShadowsOuterStaticMember.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.RulingTest/Expected/S3218.json
src/Tests/SonarLint.RulingTest/SonarLint.RulingTest.csproj
src/Tests/SonarLint.UnitTest/Rules/MemberShadowsOuterStaticMemberTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/MemberShadowsOuterStaticMember.cs

Issue #56 Inner class members should not shadow outer class "static" or type members

---

src/SonarLint/Rules/OrderByRepeatedCodeFixProvider.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.UnitTest/Rules/OrderByRepeatedTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/OrderByRepeated.Fixed.cs

Issue #158 Add codefix for S3169 (multiple OrderBy calls)

---

src/SonarLint/Rules/VirtualEventField.cs
src/SonarLint/Rules/VirtualEventFieldFixProvider.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.UnitTest/Rules/VirtualEventFieldTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/VirtualEventField.Fixed.cs

Issue #162 Add fading and codefix for S2290 (virtual field-like events)

---

src/SonarLint/Rules/OrderByRepeated.cs
src/Tests/SonarLint.UnitTest/TestCases/OrderByRepeated.Fixed.cs
src/Tests/SonarLint.UnitTest/TestCases/OrderByRepeated.cs

Issue #195 Calling OrderBy after a ThenBy doesn't make sense (S3169)

---

src/SonarLint/Rules/UnaryPrefixOperatorRepeatedCodeFixProvider.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.UnitTest/Rules/UnaryPrefixOperatorRepeatedTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/UnaryPrefixOperatorRepeated.Fixed.cs

Issue #161 Add codefix for S2761 (unary prefix operator repeated)

---

src/SonarLint/Rules/TernaryOperatorPointlessCodeFixProvider.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.UnitTest/Rules/TernaryOperatorPointlessTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/TernaryOperatorPointless.Fixed.cs

Issue #197 Add codefix to S2758 (pointless ternery operator)

---

src/SonarLint/Rules/DisposableNotDisposed.cs
src/Tests/SonarLint.UnitTest/TestCases/DisposableNotDisposed.cs

Issue #202 Add support to the Elvis operator in S2930 (Dispose of unused fields)

---

src/SonarLint/Rules.Description/S3254.html
src/SonarLint/Rules/ArrayCovariance.cs
src/SonarLint/Rules/RedundantArgument.cs
src/SonarLint/Rules/RedundantArgumentCodeFixProvider.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.RulingTest/Expected/S3254.json
src/Tests/SonarLint.RulingTest/SonarLint.RulingTest.csproj
src/Tests/SonarLint.UnitTest/Rules/RedundantArgumentTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/RedundantArgument.Named.Fixed.cs
src/Tests/SonarLint.UnitTest/TestCases/RedundantArgument.NoNamed.Fixed.cs
src/Tests/SonarLint.UnitTest/TestCases/RedundantArgument.cs

Issue #78 - Redundant argument with default value - Analyzer, CodeFix

---

src/SonarLint/Rules/CatchRethrow.cs
src/SonarLint/Rules/CatchRethrowCodeFixProvider.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.UnitTest/Rules/CatchRethrowTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/CatchRethrow.Fixed.cs
src/Tests/SonarLint.UnitTest/TestCases/CatchRethrow.cs

Issue #173 Fade out and add code fix to catch blocks with only a throw in them (S2737)

---

src/SonarLint/Rules/ThreadStaticNonStaticFieldCodeFixProvider.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.UnitTest/Rules/ThreadStaticNonStaticFieldTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/ThreadStaticNonStaticField.Fixed.cs

Issue #143 Add codefix for S3005 (non static field with ThreadStaticAttribute)

---

build/ChangeVersion.proj
src/SonarLint.Vsix/Diagnostic.nuspec
src/SonarLint.Vsix/source.extension.vsixmanifest

Issue #167 Add a link to the release notes in the VSIX and NuGet packages

---

src/SonarLint/Rules/RedundantCastCodeFixProvider.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.UnitTest/Rules/RedundantCastTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/RedundantCast.Fixed.cs

Issue #144 Add codefix for S1905 (redundant casts)

---

src/SonarLint/Rules/FieldShouldBeReadonlyCodeFixProvider.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.UnitTest/Rules/FieldShouldBeReadonlyTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/FieldShouldBeReadonly.Fixed.cs

Issue #151 Add codefix for S2933 (field should be readonly)

---

src/SonarLint/Rules/SuppressFinalizeUselessCodeFixProvider.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.UnitTest/Rules/SuppressFinalizeUselessTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/SuppressFinalizeUseless.Fixed.cs

Issue #160 Add codefix for S3234 (useless GC.SuppressFinalize)

---

src/SonarLint/Rules/SillyBitwiseOperation.cs
src/SonarLint/Rules/SillyBitwiseOperationCodeFixProvider.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.UnitTest/Rules/SillyBitwiseOperationTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/SillyBitwiseOperation.Fixed.cs

Issue #159 Improve error location, fade, and add codefix for S2437 (Silly bitwise operation)

---

src/SonarLint/Rules/BooleanCheckInverted.cs
src/SonarLint/Rules/BooleanCheckInvertedCodeFixProvider.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.UnitTest/Rules/BooleanCheckInvertedTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/BooleanCheckInverted.Fixed.cs

Issue #148 Change metadata, and add codefix to S1940 (inverted boolean check)

---

src/SonarLint/Rules/GenericReadonlyFieldPropertyAssignment.cs
src/Tests/SonarLint.UnitTest/TestCases/GenericReadonlyFieldPropertyAssignment.cs

Issue #218 Remove false positives from S2934 (Generic readonly field property assignment)

---

src/SonarLint/Rules/GenericTypeParameterEmptinessCheckingCodeFixProvider.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.UnitTest/Rules/GenericTypeParameterEmptinessCheckingTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/GenericTypeParameterEmptinessChecking.Fixed.cs

Issue #154 Add codefix for S2955 (generic type parameter emptiness checking)

---

src/SonarLint/Rules.Description/S1125.html
src/SonarLint/Rules/BooleanLiteralUnnecessary.cs
src/SonarLint/Rules/BooleanLiteralUnnecessaryCodeFixProvider.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.RulingTest/Expected/S1125.json
src/Tests/SonarLint.UnitTest/Rules/BooleanLiteralUnnecessaryTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/BooleanLiteralUnnecessary.Fixed.cs
src/Tests/SonarLint.UnitTest/TestCases/BooleanLiteralUnnecessary.cs

Issue #69 Fix error location for S1125 and add ternary operator support

---

src/SonarLint/Rules.Description/S3240.html
src/SonarLint/Rules/ConditionalSimplification.cs
src/SonarLint/Rules/ConditionalSimplificationCodeFixProvider.cs
src/SonarLint/Rules/TernaryOperatorPointless.cs
src/SonarLint/Rules/TernaryOperatorPointlessCodeFixProvider.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.RulingTest/Expected/S3240.json
src/Tests/SonarLint.RulingTest/SonarLint.RulingTest.csproj
src/Tests/SonarLint.UnitTest/Rules/ConditionalSimplificationTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/ConditionalSimplification.Fixed.cs
src/Tests/SonarLint.UnitTest/TestCases/ConditionalSimplification.cs
src/Tests/SonarLint.UnitTest/TestCases/TernaryOperatorPointless.Fixed.cs
src/Tests/SonarLint.UnitTest/TestCases/TernaryOperatorPointless.cs

Issue #67 The simplest possible condition syntax should be used

---

src/SonarLint/Rules/IfConditionalAlwaysTrueOrFalse.cs
src/SonarLint/Rules/IfConditionalAlwaysTrueOrFalseCodeFixProvider.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.UnitTest/Rules/IfConditionalAlwaysTrueOrFalseTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/IfConditionalAlwaysTrueOrFalse.Fixed.cs
src/Tests/SonarLint.UnitTest/TestCases/IfConditionalAlwaysTrueOrFalse.cs

Issue #157 Improve error location, fade, and add codefix for S1145 (if always true or false)

---

src/SonarLint/Rules/ValuesUselesslyIncremented.cs
src/Tests/SonarLint.UnitTest/TestCases/ValuesUselesslyIncremented.cs

Issue #382 S2123 reacts on fields and properties

---

src/SonarLint/Rules/BooleanLiteralUnnecessaryCodeFixProvider.cs
src/Tests/SonarLint.UnitTest/TestCases/BooleanLiteralUnnecessary.Fixed.cs
src/Tests/SonarLint.UnitTest/TestCases/BooleanLiteralUnnecessary.cs

Issue #386 Codefix fo S1125 should add parenthesis if it negates the condition

---

src/SonarLint/Rules.Description/S2292.html
src/SonarLint/Rules/PropertyToAutoProperty.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.RulingTest/Expected/S2292.json
src/Tests/SonarLint.RulingTest/SonarLint.RulingTest.csproj
src/Tests/SonarLint.UnitTest/Rules/PropertyToAutoPropertyTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/PropertyToAutoProperty.cs

Issue #174 Trivial properties should be auto-implemented

---

src/SonarLint/Rules.Description/S3263.html
src/SonarLint/Rules/StaticFieldInitializerOrder.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.RulingTest/Expected/S3263.json
src/Tests/SonarLint.RulingTest/SonarLint.RulingTest.csproj
src/Tests/SonarLint.UnitTest/Rules/StaticFieldInitializerOrderTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/StaticFieldInitializerOrder.cs

Issue #178 Static fields should appear in the order they must be initialized

---

src/SonarLint/Common/DocumentBasedFixAllProvider.cs
src/SonarLint/Rules/EmptyStatementCodeFixProvider.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.UnitTest/Rules/EmptyStatementTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/EmptyStatement.Fixed.cs

Issue #141  - Add codefix for empty statement rule (S1116)

---

src/SonarLint/Rules/PropertyToAutoProperty.cs
src/Tests/SonarLint.UnitTest/TestCases/PropertyToAutoProperty.cs

Issue #444 S2292 fails on properties with expression body

---

src/SonarLint/Rules/ValuesUselesslyIncremented.cs
src/Tests/SonarLint.UnitTest/TestCases/ValuesUselesslyIncremented.cs

Issue #384 Handle expression bodied members in S2123

---

src/SonarLint/Rules.Description/S2760.html
src/SonarLint/Rules/ConditionalsWithSameCondition.cs

Issue #383 Improve the metadata of S2760 not to show it as a bug

---

src/SonarLint.DocGenerator/RuleDescription.cs
src/SonarLint.Extra/Common/RuleDescriptors/RuleDetail.cs
src/SonarLint.Extra/Utilities/RuleDetailBuilder.cs
src/SonarQube.SonarLint.Descriptor/Descriptors/RuleDetail.cs
src/Tests/SonarLint.UnitTest/Common/RuleTest.cs

Issue #378 Improve the documentation pages

---

src/SonarLint/Rules.Description/S3246.html
src/SonarLint/Rules/GenericTypeParameterInOut.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.RulingTest/Expected/S3246.json
src/Tests/SonarLint.RulingTest/SonarLint.RulingTest.csproj
src/Tests/SonarLint.UnitTest/Rules/GenericTypeParameterInOutTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/GenericTypeParameterInOut.cs

Issue #71 Generic type parameters should be co/contravariant when possible

---

src/SonarLint/Rules/ConsoleLogging.cs
src/SonarLint/Rules/InsecureEncryptionAlgorithm.cs
src/SonarLint/Rules/InsecureHashAlgorithm.cs

Issue #451 S2228, S2278, S2070 throws null ref exception on invalid code

---

src/SonarLint/Rules/BooleanCheckInvertedCodeFixProvider.cs
src/SonarLint/Rules/BooleanLiteralUnnecessaryCodeFixProvider.cs
src/SonarLint/Rules/CatchRethrowCodeFixProvider.cs
src/SonarLint/Rules/ConditionalSimplificationCodeFixProvider.cs
src/SonarLint/Rules/IfConditionalAlwaysTrueOrFalseCodeFixProvider.cs
src/SonarLint/Rules/RedundantArgumentCodeFixProvider.cs
src/SonarLint/Rules/SillyBitwiseOperationCodeFixProvider.cs
src/SonarLint/Rules/TernaryOperatorPointlessCodeFixProvider.cs
src/SonarLint/Rules/UnaryPrefixOperatorRepeatedCodeFixProvider.cs
src/Tests/SonarLint.UnitTest/TestCases/BooleanCheckInverted.Fixed.cs
src/Tests/SonarLint.UnitTest/TestCases/BooleanCheckInverted.cs
src/Tests/SonarLint.UnitTest/TestCases/BooleanLiteralUnnecessary.Fixed.cs
src/Tests/SonarLint.UnitTest/TestCases/BooleanLiteralUnnecessary.cs
src/Tests/SonarLint.UnitTest/TestCases/CatchRethrow.Fixed.cs
src/Tests/SonarLint.UnitTest/TestCases/CatchRethrow.cs
src/Tests/SonarLint.UnitTest/TestCases/ConditionalSimplification.Fixed.cs
src/Tests/SonarLint.UnitTest/TestCases/ConditionalSimplification.cs
src/Tests/SonarLint.UnitTest/TestCases/IfConditionalAlwaysTrueOrFalse.Fixed.cs
src/Tests/SonarLint.UnitTest/TestCases/IfConditionalAlwaysTrueOrFalse.cs
src/Tests/SonarLint.UnitTest/TestCases/SillyBitwiseOperation.Fixed.cs
src/Tests/SonarLint.UnitTest/TestCases/SillyBitwiseOperation.cs
src/Tests/SonarLint.UnitTest/TestCases/TernaryOperatorPointless.Fixed.cs
src/Tests/SonarLint.UnitTest/TestCases/TernaryOperatorPointless.cs
src/Tests/SonarLint.UnitTest/TestCases/UnaryPrefixOperatorRepeated.Fixed.cs
src/Tests/SonarLint.UnitTest/TestCases/UnaryPrefixOperatorRepeated.cs

Issue #441 Only format code that has been modified in a codefix

---

src/SonarLint/Rules.Description/S3253.html
src/SonarLint/Rules/DefaultBaseConstructorCall.cs
src/SonarLint/Rules/DefaultBaseConstructorCallCodeFixProvider.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.RulingTest/Expected/S3253.json
src/Tests/SonarLint.RulingTest/SonarLint.RulingTest.csproj
src/Tests/SonarLint.UnitTest/Rules/DefaultBaseConstructorCallTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/DefaultBaseConstructorCall.Fixed.cs
src/Tests/SonarLint.UnitTest/TestCases/DefaultBaseConstructorCall.cs

Issue #179 - Default base constructor calls should not be made - Analyzer, CodeFix

---

src/SonarLint/Rules.Description/S3262.html
src/SonarLint/Rules/MethodOverrideNoParams.cs
src/SonarLint/Rules/MethodOverrideNoParamsCodeFixProvider.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.RulingTest/Expected/S3262.json
src/Tests/SonarLint.RulingTest/SonarLint.RulingTest.csproj
src/Tests/SonarLint.UnitTest/Rules/MethodOverrideNoParamsTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/MethodOverrideNoParams.Fixed.cs
src/Tests/SonarLint.UnitTest/TestCases/MethodOverrideNoParams.cs

Issue #374 "params" should be used on overrides

---

src/SonarLint/Rules.Description/S1939.html
src/SonarLint/Rules/DefaultBaseConstructorCallCodeFixProvider.cs
src/SonarLint/Rules/RedundantInheritanceList.cs
src/SonarLint/Rules/RedundantInheritanceListCodeFixProvider.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.RulingTest/Expected/S1939.json
src/Tests/SonarLint.RulingTest/SonarLint.RulingTest.csproj
src/Tests/SonarLint.UnitTest/Rules/RedundantInheritanceListTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/RedundantInheritanceList.Fixed.cs
src/Tests/SonarLint.UnitTest/TestCases/RedundantInheritanceList.cs

Issue #369 Inheritance list should not be redundant

---

src/SonarLint/Rules.Description/S2333.html
src/SonarLint/Rules/RedundantModifier.cs
src/SonarLint/Rules/RedundantModifierCodeFixProvider.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.RulingTest/Expected/S2333.json
src/Tests/SonarLint.RulingTest/SonarLint.RulingTest.csproj
src/Tests/SonarLint.UnitTest/Rules/RedundantModifierTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/RedundantModifier.Fixed.cs
src/Tests/SonarLint.UnitTest/TestCases/RedundantModifier.cs

Issue #367 Gratuitious modifiers should be removed

---

src/SonarLint/Rules.Description/S818.html
src/SonarLint/Rules/LiteralSuffixUpperCase.cs
src/SonarLint/Rules/LiteralSuffixUpperCaseCodeFixProvider.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.RulingTest/Expected/S818.json
src/Tests/SonarLint.RulingTest/SonarLint.RulingTest.csproj
src/Tests/SonarLint.UnitTest/Rules/LiteralSuffixUpperCaseTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/LiteralSuffixUpperCase.Fixed.cs
src/Tests/SonarLint.UnitTest/TestCases/LiteralSuffixUpperCase.cs

Issue #366 - Literal suffixes should be upper case

---

src/SonarLint/Rules/GetTypeWithIsAssignableFrom.cs
src/SonarLint/Rules/GetTypeWithIsAssignableFromCodeFixProvider.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.UnitTest/PackagingTests/VsixTest.cs
src/Tests/SonarLint.UnitTest/Rules/GetTypeWithIsAssignableFromTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/GetTypeWithIsAssignableFrom.Fixed.cs

Issue 398 Add codefix to S2219 (GetType with IsAssignableFrom)

---

src/SonarLint/Rules/GetHashCodeMutable.cs
src/SonarLint/Rules/GetHashCodeMutableCodeFixProvider.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.RulingTest/Expected/S2328.json
src/Tests/SonarLint.UnitTest/Rules/GetHashCodeMutableTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/GetHashCodeMutable.Fixed.cs

Issue #156 Add codefix for S2328 (GetHashCode uses mutable field)

---

src/SonarLint/Rules/EmptyMethodCodeFixProvider.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.UnitTest/Rules/EmptyMethodTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/EmptyMethod.Comment.Fixed.cs
src/Tests/SonarLint.UnitTest/TestCases/EmptyMethod.Throw.Fixed.cs

Issue #147 Add codefix for S1186 (empty method)

---

src/SonarLint/Rules/GenericReadonlyFieldPropertyAssignmentCodeFixProvider.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.UnitTest/Rules/GenericReadonlyFieldPropertyAssignmentTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/GenericReadonlyFieldPropertyAssignment.AddConstraint.Fixed.cs
src/Tests/SonarLint.UnitTest/TestCases/GenericReadonlyFieldPropertyAssignment.Remove.Fixed.cs

Issue #153 Add codefix for S2934 (property assignment of a generic readonly field)

---

src/SonarLint/Rules/IfConditionalAlwaysTrueOrFalseCodeFixProvider.cs

Issue #436 Use improved FixAllProvider for S1145

---

src/SonarLint/Rules/BooleanCheckInvertedCodeFixProvider.cs
src/Tests/SonarLint.UnitTest/TestCases/BooleanCheckInverted.Fixed.cs
src/Tests/SonarLint.UnitTest/TestCases/BooleanCheckInverted.cs

Issue #229 Fix the codefix for S1940 (inverted boolean check)

---

src/SonarLint/Common/DocumentBasedFixAllProvider.cs
src/SonarLint/Rules/EmptyStatementCodeFixProvider.cs
src/SonarLint/Rules/IfConditionalAlwaysTrueOrFalseCodeFixProvider.cs
src/SonarLint/Rules/SillyBitwiseOperationCodeFixProvider.cs

Issue #228 Use improved FixAllProvider for S2437

---

src/SonarLint/Rules/SuppressFinalizeUselessCodeFixProvider.cs

Issue #207 Use improved FixAllProvider for S3234

---

src/SonarLint/Common/DocumentBasedFixAllProvider.cs
src/SonarLint/Rules/RedundantCastCodeFixProvider.cs
src/Tests/SonarLint.UnitTest/TestCases/RedundantCast.Fixed.cs
src/Tests/SonarLint.UnitTest/TestCases/RedundantCast.cs

Issue #208 Use improved FixAllProvider for S1905

---

src/SonarLint/Rules/CatchRethrowCodeFixProvider.cs

Issue #435 Use improved FixAllProvider for S2737

---

src/SonarLint/Rules.Description/S1645.html
src/SonarLint/Rules/StringConcatenationWithPlus.cs
src/SonarLint/Rules/StringConcatenationWithPlusCodeFixProvider.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.RulingTest/Expected/VisualBasic/S1645.json
src/Tests/SonarLint.RulingTest/SonarLint.RulingTest.csproj
src/Tests/SonarLint.UnitTest/Rules/StringConcatenationWithPlusTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/StringConcatenationWithPlus.Fixed.vb
src/Tests/SonarLint.UnitTest/TestCases/StringConcatenationWithPlus.vb

String concat with plus

---

src/SonarLint/Rules.Description/S2352.html
src/SonarLint/Rules/IndexedPropertyWithMultipleParameters.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.RulingTest/Expected/VisualBasic/S2352.json
src/Tests/SonarLint.RulingTest/SonarLint.RulingTest.csproj
src/Tests/SonarLint.UnitTest/Rules/IndexedPropertyWithMultipleParametersTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/IndexedPropertyWithMultipleParameters.vb

Indexed properties

---

src/SonarLint/Rules.Description/S2365.html
src/SonarLint/Rules/PropertyWithArrayType.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.RulingTest/Expected/VisualBasic/S2365.json
src/Tests/SonarLint.RulingTest/SonarLint.RulingTest.csproj
src/Tests/SonarLint.UnitTest/Rules/PropertyWithArrayTypeTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/PropertyWithArrayType.vb

Issue #492 Properties should not be based on arrays

---

src/SonarLint/Rules.Description/S2351.html
src/SonarLint/Rules/ArrayInitializationMultipleStatements.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.RulingTest/Expected/VisualBasic/S2351.json
src/Tests/SonarLint.RulingTest/SonarLint.RulingTest.csproj
src/Tests/SonarLint.UnitTest/Rules/ArrayInitializationMultipleStatementsTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/ArrayInitializationMultipleStatements.vb

Issue #477 Arrays should be initialized using the "... = {}" syntax

---

src/SonarLint/Rules.Description/S2355.html
src/SonarLint/Rules/ArrayCreationLongSyntax.cs
src/SonarLint/Rules/ArrayCreationLongSyntaxCodeFixProvider.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.RulingTest/Expected/VisualBasic/S2355.json
src/Tests/SonarLint.RulingTest/SonarLint.RulingTest.csproj
src/Tests/SonarLint.UnitTest/PackagingTests/VsixTest.cs
src/Tests/SonarLint.UnitTest/Rules/ArrayCreationLongSyntaxTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/ArrayCreationLongSyntax.Fixed.vb
src/Tests/SonarLint.UnitTest/TestCases/ArrayCreationLongSyntax.vb

Array literals should be used instead of array creation expressions

---

src/SonarLint.Vsix/Diagnostic.nuspec
src/SonarLint.Vsix/tools/install.ps1
src/SonarLint.Vsix/tools/uninstall.ps1

Issue #540 Change nuget package generation to support multiple languages

---

build/Version.props
src/AssemblyInfo.Shared.cs
src/SonarLint.Vsix/Diagnostic.nuspec
src/SonarLint.Vsix/source.extension.vsixmanifest
src/SonarQube.SonarLint.Descriptor/Descriptor.nuspec
src/SonarQube.SonarLint.Runner/Runner.nuspec

Issue #541 Change version and package metadata

---

src/SonarLint/Rules/BooleanCheckInvertedCodeFixProvider.cs
src/SonarLint/Rules/BooleanLiteralUnnecessaryCodeFixProvider.cs
src/SonarLint/Rules/GetTypeWithIsAssignableFromCodeFixProvider.cs
src/SonarLint/Rules/LiteralSuffixUpperCaseCodeFixProvider.cs
src/SonarLint/Rules/NegatedIsExpressionCodeFixProvider.cs
src/SonarLint/Rules/SillyBitwiseOperationCodeFixProvider.cs
src/SonarLint/Rules/TernaryOperatorPointlessCodeFixProvider.cs
src/SonarLint/Rules/UnaryPrefixOperatorRepeatedCodeFixProvider.cs
src/Tests/SonarLint.UnitTest/TestCases/BooleanCheckInverted.Fixed.cs
src/Tests/SonarLint.UnitTest/TestCases/BooleanCheckInverted.cs
src/Tests/SonarLint.UnitTest/TestCases/BooleanLiteralUnnecessary.Fixed.cs
src/Tests/SonarLint.UnitTest/TestCases/BooleanLiteralUnnecessary.cs
src/Tests/SonarLint.UnitTest/TestCases/GetTypeWithIsAssignableFrom.Fixed.cs
src/Tests/SonarLint.UnitTest/TestCases/GetTypeWithIsAssignableFrom.cs
src/Tests/SonarLint.UnitTest/TestCases/LiteralSuffixUpperCase.Fixed.cs
src/Tests/SonarLint.UnitTest/TestCases/LiteralSuffixUpperCase.cs
src/Tests/SonarLint.UnitTest/TestCases/NegatedIsExpression.Fixed.vb
src/Tests/SonarLint.UnitTest/TestCases/NegatedIsExpression.vb
src/Tests/SonarLint.UnitTest/TestCases/SillyBitwiseOperation.Fixed.cs
src/Tests/SonarLint.UnitTest/TestCases/SillyBitwiseOperation.cs
src/Tests/SonarLint.UnitTest/TestCases/TernaryOperatorPointless.Fixed.cs
src/Tests/SonarLint.UnitTest/TestCases/TernaryOperatorPointless.cs
src/Tests/SonarLint.UnitTest/TestCases/UnaryPrefixOperatorRepeated.Fixed.cs
src/Tests/SonarLint.UnitTest/TestCases/UnaryPrefixOperatorRepeated.cs

Issue #515 Improve codefixes to correctly find reported error locations

---

src/SonarLint/Rules.Description/S1147.html
src/SonarLint/Rules/EndStatementUsage.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.RulingTest/Expected/VisualBasic/S1147.json
src/Tests/SonarLint.RulingTest/SonarLint.RulingTest.csproj
src/Tests/SonarLint.UnitTest/Rules/EndStatementUsageTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/EndStatementUsage.vb

Issue #474 End statements should not be used

---

src/SonarLint/Rules.Description/S2346_cs.html
src/SonarLint/Rules.Description/S2346_vb.html
src/SonarLint/Rules/FlagsEnumZeroMember.cs
src/SonarLint/Rules/FlagsEnumZeroMemberBase.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.RulingTest/Expected/CSharp/S2346.json
src/Tests/SonarLint.RulingTest/Expected/VisualBasic/S2346.json
src/Tests/SonarLint.RulingTest/SonarLint.RulingTest.csproj
src/Tests/SonarLint.UnitTest/Rules/FlagsEnumZeroMemberTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/FlagsEnumZeroMember.cs
src/Tests/SonarLint.UnitTest/TestCases/FlagsEnumZeroMember.vb

Flags zero

---

src/SonarLint/Rules.Description/S2345_cs.html
src/SonarLint/Rules.Description/S2345_vb.html
src/SonarLint/Rules/FlagsEnumWithoutInitializer.cs
src/SonarLint/Rules/FlagsEnumWithoutInitializerBase.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.RulingTest/Expected/CSharp/S2345.json
src/Tests/SonarLint.RulingTest/Expected/VisualBasic/S2345.json
src/Tests/SonarLint.RulingTest/SonarLint.RulingTest.csproj
src/Tests/SonarLint.UnitTest/Rules/FlagsEnumWithoutInitializerTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/FlagsEnumWithoutInitializer.cs
src/Tests/SonarLint.UnitTest/TestCases/FlagsEnumWithoutInitializer.vb

Flags init

---

src/SonarLint/Rules.Description/S1226_cs.html
src/SonarLint/Rules.Description/S1226_vb.html
src/SonarLint/Rules/ParameterAssignedTo.cs
src/SonarLint/Rules/ParameterAssignedToBase.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.RulingTest/Expected/VisualBasic/S1226.json
src/Tests/SonarLint.RulingTest/SonarLint.RulingTest.csproj
src/Tests/SonarLint.UnitTest/Rules/ParameterAssignedToTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/ParameterAssignedTo.vb

Param reassigned

---

src/SonarLint/Rules.Description/S2372_cs.html
src/SonarLint/Rules.Description/S2372_vb.html
src/SonarLint/Rules/PropertyGetterWithThrow.cs
src/SonarLint/Rules/PropertyGetterWithThrowBase.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.RulingTest/Expected/CSharp/S2372.json
src/Tests/SonarLint.RulingTest/Expected/VisualBasic/S2372.json
src/Tests/SonarLint.RulingTest/SonarLint.RulingTest.csproj
src/Tests/SonarLint.UnitTest/Rules/PropertyGetterWithThrowTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/PropertyGetterWithThrow.cs
src/Tests/SonarLint.UnitTest/TestCases/PropertyGetterWithThrow.vb

Exception thrown in property getter

---

src/SonarLint/Rules.Description/S2376_cs.html
src/SonarLint/Rules.Description/S2376_vb.html
src/SonarLint/Rules/PropertyWriteOnly.cs
src/SonarLint/Rules/PropertyWriteOnlyBase.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.RulingTest/Expected/CSharp/S2376.json
src/Tests/SonarLint.RulingTest/Expected/VisualBasic/S2376.json
src/Tests/SonarLint.RulingTest/SonarLint.RulingTest.csproj
src/Tests/SonarLint.UnitTest/Rules/PropertyWriteOnlyTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/PropertyWriteOnly.cs
src/Tests/SonarLint.UnitTest/TestCases/PropertyWriteOnly.vb

Prop only set

---

src/SonarLint/Rules.Description/S2368_cs.html
src/SonarLint/Rules.Description/S2368_vb.html
src/SonarLint/Rules/PublicMethodWithMultidimensionalArray.cs
src/SonarLint/Rules/PublicMethodWithMultidimensionalArrayBase.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.RulingTest/Expected/CSharp/S2368.json
src/Tests/SonarLint.RulingTest/Expected/VisualBasic/S2368.json
src/Tests/SonarLint.RulingTest/SonarLint.RulingTest.csproj
src/Tests/SonarLint.UnitTest/Rules/PublicMethodWithMultidimensionalArrayTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/PublicMethodWithMultidimensionalArray.cs
src/Tests/SonarLint.UnitTest/TestCases/PublicMethodWithMultidimensionalArray.vb

Public method with multi

---

src/SonarLint.DocGenerator/Program.cs
src/SonarLint.DocGenerator/RuleDescription.cs
src/SonarLint.DocGenerator/SonarLint.DocGenerator.csproj
src/SonarLint.DocGenerator/packages.config
src/Tests/SonarLint.UnitTest/PackagingTests/DocGeneratorTest.cs

Web multi lang

---

build/ChangeVersion.proj
build/generate_rule_descriptor.bat
build/release_internal.bat
src/SonarLint.DocGenerator/packages.config
src/SonarLint.Extra/packages.config
src/SonarLint/packages.config
src/SonarQube.SonarLint.Descriptor/Descriptor.cs.nuspec
src/SonarQube.SonarLint.Descriptor/Descriptor.csproj
src/SonarQube.SonarLint.Descriptor/Descriptor.vbnet.nuspec
src/SonarQube.SonarLint.Descriptor/Program.cs
src/SonarQube.SonarLint.Descriptor/packages.config
src/Tests/SonarLint.RulingTest/packages.config
src/Tests/SonarLint.SonarQube.Integration.UnitTest/packages.config

Descriptor nuget

---

src/SonarLint/Rules.Description/S1313.html
src/SonarLint/Rules/HardcodedIpAddress.cs
src/Tests/SonarLint.RulingTest/Expected/CSharp/S1313.json
src/Tests/SonarLint.UnitTest/TestCases/HardcodedIpAddress.cs

Issue #520 S1313 should not report on string literal "::"

---

src/SonarLint/Rules/ClassShouldNotBeAbstract.cs
src/Tests/SonarLint.RulingTest/Expected/CSharp/S1694.json
src/Tests/SonarLint.UnitTest/TestCases/ClassShouldNotBeAbstract.cs

S1694 should not report on classes that have derived abstract methods

---

src/SonarLint/Rules.Description/S2339_cs.html
src/SonarLint/Rules.Description/S2339_vb.html
src/SonarLint/Rules/PublicConstantField.cs
src/SonarLint/Rules/PublicConstantFieldBase.cs
src/SonarLint/Rules/PublicMethodWithMultidimensionalArrayBase.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.RulingTest/Expected/CSharp/S2339.json
src/Tests/SonarLint.RulingTest/Expected/VisualBasic/S2339.json
src/Tests/SonarLint.RulingTest/SonarLint.RulingTest.csproj
src/Tests/SonarLint.UnitTest/PackagingTests/VsixTest.cs
src/Tests/SonarLint.UnitTest/Rules/PublicConstantFieldTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/PublicConstantField.cs
src/Tests/SonarLint.UnitTest/TestCases/PublicConstantField.vb

Constant members

---

src/SonarLint/Rules/RedundantModifier.cs
src/Tests/SonarLint.UnitTest/TestCases/RedundantModifier.Fixed.cs
src/Tests/SonarLint.UnitTest/TestCases/RedundantModifier.cs

Issue #523 S2333 - False positive on generic base classes

---

src/SonarLint/Rules/BooleanLiteralUnnecessary.cs
src/Tests/SonarLint.RulingTest/Expected/CSharp/S1125.json
src/Tests/SonarLint.UnitTest/TestCases/BooleanLiteralUnnecessary.Fixed.cs
src/Tests/SonarLint.UnitTest/TestCases/BooleanLiteralUnnecessary.cs

Issue #461 S1125 should not report on nullable booleans

---

src/SonarLint/Rules/GenericTypeParameterUnused.cs
src/Tests/SonarLint.RulingTest/Expected/CSharp/S2326.json
src/Tests/SonarLint.UnitTest/TestCases/GenericTypeParameterUnused.cs

S2326 shouldn't report on type parameter only used in type constraint

---

src/SonarLint/Rules.Description/S2340.html
src/SonarLint/Rules/SimpleDoLoop.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.RulingTest/Expected/VisualBasic/S2340.json
src/Tests/SonarLint.RulingTest/SonarLint.RulingTest.csproj
src/Tests/SonarLint.UnitTest/Rules/SimpleDoLoopTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/SimpleDoLoop.vb

"Do" loops should not be used without a "While" or "Until" condition

---

src/SonarLint/Rules.Description/S2350.html
src/SonarLint/Rules/RedundantExitSelect.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.RulingTest/Expected/VisualBasic/S2350.json
src/Tests/SonarLint.RulingTest/SonarLint.RulingTest.csproj
src/Tests/SonarLint.UnitTest/Rules/RedundantExitSelectTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/RedundantExitSelect.vb

Issue #473 "Exit Select" statements should not be used redundantly

---

src/SonarLint/Rules/ConstructorOverridableCall.cs
src/Tests/SonarLint.UnitTest/TestCases/ConstructorOverridableCall.cs

S1699 should not report on virtual methods called on other instances

---

src/SonarLint/Rules.Description/S3385.html
src/SonarLint/Rules/ExitStatementUsage.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.RulingTest/Expected/VisualBasic/S3385.json
src/Tests/SonarLint.RulingTest/SonarLint.RulingTest.csproj
src/Tests/SonarLint.UnitTest/Rules/ExitStatementUsageTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/ExitStatementUsage.vb

Issue #529 "Exit" statements should not be used

---

src/SonarLint/Rules.Description/S2360_cs.html
src/SonarLint/Rules.Description/S2360_vb.html
src/SonarLint/Rules/OptionalParameter.cs
src/SonarLint/Rules/OptionalParameterBase.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.RulingTest/Expected/CSharp/S2360.json
src/Tests/SonarLint.RulingTest/Expected/VisualBasic/S2360.json
src/Tests/SonarLint.RulingTest/SonarLint.RulingTest.csproj
src/Tests/SonarLint.UnitTest/Rules/OptionalParameterTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/OptionalParameter.cs
src/Tests/SonarLint.UnitTest/TestCases/OptionalParameter.vb

Issue #488 Optional arguments should not be used

---

src/SonarLint/Rules/IndexOfCheckAgainstZero.cs
src/SonarLint/Rules/MethodParameterUnused.cs
src/Tests/SonarLint.RulingTest/Expected/CSharp/S1172.json
src/Tests/SonarLint.UnitTest/TestCases/MethodParameterUnused.cs

Issue #211 S1172 should not report on event handlers

---

src/SonarLint/Rules/CommentedOutCode.cs
src/Tests/SonarLint.RulingTest/Expected/CSharp/S125.json
src/Tests/SonarLint.UnitTest/TestCases/CommentedOutCode.cs

Issue #519 Reduce the number of issues reported by S125

---

src/SonarLint/Rules/StaticFieldInitializerOrder.cs
src/Tests/SonarLint.UnitTest/TestCases/StaticFieldInitializerOrder.cs

Issue #581 S3263 shouldn't report on constant initializer values

---

src/SonarLint/Rules.Description/S122_cs.html
src/SonarLint/Rules.Description/S122_vb.html
src/SonarLint/Rules/SingleStatementPerLine.cs
src/SonarLint/Rules/SingleStatementPerLineBase.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.RulingTest/Expected/CSharp/S122.json
src/Tests/SonarLint.RulingTest/Expected/VisualBasic/S122.json
src/Tests/SonarLint.RulingTest/SonarLint.RulingTest.csproj
src/Tests/SonarLint.UnitTest/Rules/SingleStatementPerLineTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/SingleStatementPerLine.cs
src/Tests/SonarLint.UnitTest/TestCases/SingleStatementPerLine.vb

Issue #487 Statements should be on separate lines

---

src/SonarLint/Rules/FileLines.cs
src/Tests/SonarLint.RulingTest/Expected/CSharp/S104.json

Improve parametered

---

src/SonarLint/Rules/LineLength.cs

Line length

---

src/SonarLint/Rules/FunctionComplexity.cs
src/Tests/SonarLint.RulingTest/Expected/CSharp/S1541.json

Function complexity

---

src/SonarLint/Rules.Description/S100.html
src/SonarLint/Rules/MethodName.cs
src/Tests/SonarLint.UnitTest/Rules/MethodNameTest.cs
src/Tests/SonarLint.UnitTest/TestCases/MethodName.cs

Method naming

---

src/SonarLint/Rules.Description/S101.html
src/SonarLint/Rules/ClassName.cs
src/Tests/SonarLint.RulingTest/Expected/CSharp/S101.json
src/Tests/SonarLint.UnitTest/Rules/ClassNameTest.cs
src/Tests/SonarLint.UnitTest/TestCases/ClassName.cs

Class naming

---

src/SonarLint/Rules/ConditionalSimplification.cs
src/SonarLint/Rules/ConditionalSimplificationCodeFixProvider.cs
src/Tests/SonarLint.RulingTest/Expected/CSharp/S3240.json
src/Tests/SonarLint.UnitTest/TestCases/ConditionalSimplification.Fixed.cs
src/Tests/SonarLint.UnitTest/TestCases/ConditionalSimplification.cs

Issue #406 S3240 should not report on any pattern that is not fixable

---

src/SonarLint/Helpers/EquivalenceChecker.cs
src/SonarLint/Rules.Description/S1643_cs.html
src/SonarLint/Rules.Description/S1643_vb.html
src/SonarLint/Rules/StringConcatenationInLoop.cs
src/SonarLint/Rules/StringConcatenationInLoopBase.cs
src/SonarLint/SonarLint.csproj
src/Tests/SonarLint.RulingTest/Expected/CSharp/S1643.json
src/Tests/SonarLint.RulingTest/Expected/VisualBasic/S1643.json
src/Tests/SonarLint.RulingTest/SonarLint.RulingTest.csproj
src/Tests/SonarLint.UnitTest/Rules/StringConcatenationInLoopTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/StringConcatenationInLoop.cs
src/Tests/SonarLint.UnitTest/TestCases/StringConcatenationInLoop.vb

Issue #467 Strings should not be concatenated using '+' in a loop

---

src/SonarLint/Rules/ClassName.cs
src/SonarLint/Rules/ExpressionComplexity.cs
src/SonarLint/Rules/FileLines.cs
src/SonarLint/Rules/FunctionComplexity.cs
src/SonarLint/Rules/LineLength.cs
src/SonarLint/Rules/MethodName.cs
src/SonarLint/Rules/TooManyLabelsInSwitch.cs
src/SonarLint/Rules/TooManyParameters.cs

Issue #614 Add descriptions and help links to parametered rules

---

src/SonarLint/Helpers/ProjectTypeHelper.cs
src/SonarLint/Rules/PropertyGetterWithThrowBase.cs
src/Tests/SonarLint.UnitTest/Verifier.cs

Issue #590 Improve test recognition

---

src/SonarLint.CSharp/Rules/GetHashCodeEqualsOverride.cs
src/SonarLint.Extra/Rules.Description/S3249.html
src/Tests/SonarLint.UnitTest/TestCases/GetHashCodeEqualsOverride.cs

Issue #521 S3249 should not report on reference equality guard conditions in Equals

---

src/SonarLint.CSharp/Rules/MethodParameterUnused.cs
src/SonarLint.Extra/Rules.Description/S1172.html
src/Tests/SonarLint.RulingTest/Expected/CSharp/S1172.json
src/Tests/SonarLint.UnitTest/TestCases/MethodParameterUnused.cs

Issue #509 S1172 shouldn't report on extension methods' "this" parameter

---

src/SonarLint.CSharp/Rules/FieldShadowsParentField.cs
src/SonarLint.CSharp/Rules/StringOperationWithoutCulture.cs
src/SonarLint.CSharp/SonarLint.CSharp.csproj
src/SonarLint.Extra/Rules.Description/S1449.html
src/SonarLint.Extra/SonarLint.Extra.csproj
src/SonarLint.Test.ruleset
src/SonarLint.ruleset
src/SonarLint/Common/Tag.cs
src/SonarQube.SonarLint.Runner/Configuration.cs
src/Tests/SonarLint.RulingTest/Expected/CSharp/S1449.json
src/Tests/SonarLint.RulingTest/SonarLint.RulingTest.csproj
src/Tests/SonarLint.UnitTest/Rules/StringOperationWithoutCultureTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/StringOperationWithoutCulture.cs

Issue #180 Locale should be used in String operations

---

src/SonarLint.CSharp/Helpers/TypeHelper.cs
src/SonarLint.CSharp/Rules/CollectionQuerySimplification.cs
src/SonarLint.CSharp/Rules/IndexOfCheckAgainstZero.cs
src/SonarLint.CSharp/Rules/MethodParameterUnused.cs
src/SonarLint.CSharp/SonarLint.CSharp.csproj
src/Tests/SonarLint.UnitTest/TestCases/CollectionQuerySimplification.cs

Issue #363 Simplify the LINQ call chain

---

src/SonarLint.CSharp/Helpers/MethodParameterLookup.cs
src/SonarLint.CSharp/Rules/ArgumentSpecifiedForCallerInfoParameter.cs
src/SonarLint.CSharp/Rules/ArrayCovariance.cs
src/SonarLint.CSharp/Rules/InvocationResolvesToOverrideWithParams.cs
src/SonarLint.CSharp/Rules/ParametersCorrectOrder.cs
src/SonarLint.CSharp/Rules/RedundantArgument.cs
src/SonarLint.CSharp/Rules/RedundantArgumentCodeFixProvider.cs
src/SonarLint.CSharp/SonarLint.CSharp.csproj
src/SonarLint.Extra/Rules.Description/S3220.html
src/SonarLint.Extra/SonarLint.Extra.csproj
src/Tests/SonarLint.RulingTest/Expected/CSharp/S3220.json
src/Tests/SonarLint.RulingTest/SonarLint.RulingTest.csproj
src/Tests/SonarLint.UnitTest/Rules/InvocationResolvesToOverrideWithParamsTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/InvocationResolvesToOverrideWithParams.cs

Method calls should not resolve ambiguously to overloads with "params"

---

src/SonarLint.CSharp/Rules/MethodOverloadOptionalParameter.cs
src/SonarLint.CSharp/SonarLint.CSharp.csproj
src/SonarLint.Extra/Rules.Description/S3427.html
src/SonarLint.Extra/SonarLint.Extra.csproj
src/SonarLint/Rules/PublicMethodWithMultidimensionalArrayBase.cs
src/Tests/SonarLint.RulingTest/Expected/CSharp/S3427.json
src/Tests/SonarLint.RulingTest/SonarLint.RulingTest.csproj
src/Tests/SonarLint.UnitTest/Rules/MethodOverloadOptionalParameterTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/MethodOverloadOptionalParameter.cs

Method overloads with default parameter values should not overlap

---

src/SonarLint.CSharp/Rules/StreamReadStatement.cs
src/SonarLint.CSharp/SonarLint.CSharp.csproj
src/SonarLint.Extra/Rules.Description/S2674.html
src/SonarLint.Extra/SonarLint.Extra.csproj
src/Tests/SonarLint.RulingTest/Expected/CSharp/S2674.json
src/Tests/SonarLint.RulingTest/SonarLint.RulingTest.csproj
src/Tests/SonarLint.UnitTest/Rules/StreamReadStatementTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/StreamReadStatement.cs

Issue #70 The value returned from a stream read should be checked

---

src/SonarLint.CSharp/Rules/EnumerableSumInUnchecked.cs
src/SonarLint.CSharp/SonarLint.CSharp.csproj
src/SonarLint.Extra/Rules.Description/S2291.html
src/SonarLint.Extra/SonarLint.Extra.csproj
src/Tests/SonarLint.RulingTest/Expected/CSharp/S2291.json
src/Tests/SonarLint.RulingTest/SonarLint.RulingTest.csproj
src/Tests/SonarLint.UnitTest/Rules/EnumerableSumInUncheckedTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/EnumerableSumInUnchecked.cs

Issue #177 Overflow checking should not be disabled for "Enumerable.Sum"

---

src/SonarLint.CSharp/Rules/TaskConfigureAwait.cs
src/SonarLint.CSharp/SonarLint.CSharp.csproj
src/SonarLint.Extra/Rules.Description/S3216.html
src/SonarLint.Extra/SonarLint.Extra.csproj
src/Tests/SonarLint.RulingTest/Expected/CSharp/S3216.json
src/Tests/SonarLint.RulingTest/SonarLint.RulingTest.csproj
src/Tests/SonarLint.UnitTest/Rules/TaskConfigureAwaitTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/TaskConfigureAwait.cs

Issue #360 "ConfigureAwait(false)" should be used

---

src/SonarLint.CSharp/Rules/AsyncVoidMethod.cs
src/SonarLint.CSharp/SonarLint.CSharp.csproj
src/SonarLint.Extra/Rules.Description/S3168.html
src/SonarLint.Extra/SonarLint.Extra.csproj
src/Tests/SonarLint.RulingTest/Expected/CSharp/S3168.json
src/Tests/SonarLint.RulingTest/SonarLint.RulingTest.csproj
src/Tests/SonarLint.UnitTest/Rules/AsyncVoidMethodTest.cs
src/Tests/SonarLint.UnitTest/SonarLint.UnitTest.csproj
src/Tests/SonarLint.UnitTest/TestCases/AsyncVoidMethod.cs

Issue #60 "async" methods should not return "void"

---

its/ExtractAnalyzerPerformancesFromLogs.ps1
its/SonarLint.Testing.ImportBefore.targets
its/regression-test.bat

#722 Measure the performance of each analyzer in the ruling test

---

src/SonarLint.CSharp/Rules/ReversedOperators.cs
src/SonarLint.Extra/Rules.Description/S2757.html
src/Tests/SonarLint.UnitTest/TestCases/ReversedOperators.cs

https://jira.sonarsource.com/browse/SLVS-825

SLVS-825 Improve S2757 to handle "=!"

---

src/SonarAnalyzer.Vsix/source.extension.vsixmanifest

Version range is changed to allow installation on Visual Studio 2017 RC

Visual Studio 2017 RC compatibility
